# Generated by Django 4.2.9 on 2025-02-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_userprofile_batch_alter_userprofile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='batch',
            field=models.CharField(blank=True, choices=[('2022-2026', '2022-2026'), ('2023-2027', '2023-2027')], max_length=10, null=True),
        ),
    ]
