# Generated by Django 4.2.9 on 2025-02-20 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_event_eligible_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eligible_departments',
        ),
    ]
