# Generated by Django 4.2.9 on 2025-02-20 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_remove_event_eligible_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=100)),
                ('mail_id', models.EmailField(editable=False, max_length=254, unique=True)),
                ('department', models.CharField(blank=True, choices=[('BE-BME', 'B.E. - BIOMEDICAL ENGINEERING'), ('BE-EIE', 'B.E. - ELECTRONICS AND INSTRUMENTATION ENGINEERING'), ('BE-ECE', 'B.E. - ELECTRONICS AND COMMUNICATION ENGINEERING'), ('BE-EEE', 'B.E. - ELECTRICAL AND ELECTRONICS ENGINEERING'), ('BE-CSE', 'B.E. - COMPUTER SCIENCE AND ENGINEERING'), ('BE-CSD', 'B.E. - COMPUTER SCIENCE AND DESIGN'), ('BE-CIVIL', 'B.E. - CIVIL ENGINEERING'), ('BE-ISE', 'B.E. - INFORMATION SCIENCE AND ENGINEERING'), ('BE-MECH', 'B.E. - MECHANICAL ENGINEERING'), ('BE-MCT', 'B.E. - MECHATRONICS ENGINEERING'), ('BTECH-BT', 'B.Tech. - BIOTECHNOLOGY'), ('BTECH-AGE', 'B.Tech. - AGRICULTURAL ENGINEERING'), ('BTECH-AIDS', 'B.Tech. - ARTIFICIAL INTELLIGENCE AND DATA SCIENCE'), ('BTECH-AIML', 'B.Tech. - ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING'), ('BTECH-CSBS', 'B.Tech. - COMPUTER SCIENCE AND BUSINESS SYSTEMS'), ('BTECH-CT', 'B.Tech. - COMPUTER TECHNOLOGY'), ('BTECH-FT', 'B.Tech. - FASHION TECHNOLOGY'), ('BTECH-FDT', 'B.Tech. - FOOD TECHNOLOGY'), ('BTECH-IT', 'B.Tech. - INFORMATION TECHNOLOGY'), ('ME-CS', 'M.E. - COMMUNICATION SYSTEMS'), ('ME-CSE', 'M.E. - COMPUTER SCIENCE AND ENGINEERING'), ('ME-ISE', 'M.E. - INDUSTRIAL SAFETY ENGINEERING'), ('ME-SE', 'M.E. - STRUCTURAL ENGINEERING'), ('MBA', 'M.B.A. - MASTER OF BUSINESS ADMINISTRATION'), ('PHD-BT', 'Ph.D BIOTECHNOLOGY'), ('PHD-CHEM', 'Ph.D CHEMISTRY'), ('PHD-CIVIL', 'Ph.D CIVIL ENGINEERING'), ('PHD-CSE', 'Ph.D COMPUTER SCIENCE AND ENGINEERING'), ('PHD-EEE', 'Ph.D ELECTRICAL AND ELECTRONICS ENGINEERING'), ('PHD-ECE', 'Ph.D ELECTRONICS AND COMMUNICATION ENGINEERING'), ('PHD-EIE', 'Ph.D ELECTRONICS AND INSTRUMENTATION ENGINEERING'), ('PHD-IT', 'Ph.D INFORMATION TECHNOLOGY'), ('PHD-MATH', 'Ph.D MATHEMATICS'), ('PHD-MECH', 'Ph.D MECHANICAL ENGINEERING'), ('PHD-MCT', 'Ph.D MECHATRONICS'), ('PHD-PHY', 'Ph.D PHYSICS'), ('PHD-SMS', 'Ph.D SCHOOL OF MANAGEMENT STUDIES'), ('ELCC', 'ELCC'), ('DEPT-PHY', 'DEPARTMENT OF PHYSICS'), ('DEPT-MATH', 'DEPARTMENT OF MATHEMATICS'), ('DEPT-CHEM', 'DEPARTMENT OF CHEMISTRY')], editable=False, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_levels', models.ManyToManyField(blank=True, related_name='achieved_by', to='home.levels')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['name'],
            },
        ),
    ]
