# Generated by Django 4.2.9 on 2025-02-20 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='levels',
            name='rerequisite',
            field=models.ForeignKey(blank=True, help_text='Level that must be completed before this one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_levels', to='home.levels', verbose_name='Prerequisite Level'),
        ),
    ]
