# Generated by Django 4.2.9 on 2025-02-20 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_levels_rerequisite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='levels',
            old_name='rerequisite',
            new_name='prerequisite',
        ),
    ]
