# Generated by Django 4.2.9 on 2025-02-20 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_rerequisite_levels_prerequisite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='finished_levels',
        ),
        migrations.AddField(
            model_name='achievements',
            name='finished_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achieved_by', to='home.levels'),
        ),
    ]
