# Generated by Django 4.2.9 on 2025-02-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_achievements_finished_levels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='mail_id',
            field=models.EmailField(editable=False, max_length=254),
        ),
    ]
