# Generated by Django 4.2.9 on 2025-02-20 07:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_alter_achievements_mail_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='achievements',
            unique_together={('user',)},
        ),
    ]
