# Generated by Django 4.2.9 on 2025-02-20 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0013_alter_achievements_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='achievements',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
    ]
