# Generated by Django 4.2.9 on 2025-02-20 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_achievements_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='home.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievements',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
