# Generated by Django 4.2.9 on 2025-02-21 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_achievements_event_achievements_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levels',
            name='first_mark',
        ),
        migrations.RemoveField(
            model_name='levels',
            name='maximum_capacity',
        ),
        migrations.RemoveField(
            model_name='levels',
            name='question10_mark',
        ),
        migrations.RemoveField(
            model_name='levels',
            name='question11_mark',
        ),
        migrations.RemoveField(
            model_name='levels',
            name='question12_mark',
        ),
        migrations.RemoveField(
            model_name='levels',
            name='question1_mark',
        ),
        migrations.RemoveField(
            model_name='levels',
            name='question2_mark',
        ),
        migrations.RemoveField(
            model_name='levels',
            name='question3_mark',
        ),
        migrations.RemoveField(
            model_name='levels',
            name='question4_mark',
        ),
        migrations.RemoveField(
            model_name='levels',
            name='question5_mark',
        ),
        migrations.RemoveField(
            model_name='levels',
            name='question6_mark',
        ),
        migrations.RemoveField(
            model_name='levels',
            name='question7_mark',
        ),
        migrations.RemoveField(
            model_name='levels',
            name='question8_mark',
        ),
        migrations.RemoveField(
            model_name='levels',
            name='question9_mark',
        ),
        migrations.RemoveField(
            model_name='levels',
            name='second_mark',
        ),
        migrations.RemoveField(
            model_name='levels',
            name='team_size',
        ),
        migrations.RemoveField(
            model_name='levels',
            name='third_mark',
        ),
    ]
