# Generated by Django 4.2.9 on 2025-02-21 06:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_levels_first_mark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='topic',
        ),
        migrations.AddField(
            model_name='slot',
            name='maximum_capacity',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of participants', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='slot',
            name='team_size',
            field=models.PositiveIntegerField(default=1, help_text='Number of participants per team', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='slot',
            name='slot_endtime',
            field=models.TimeField(editable=False),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='home.levels')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['level', 'topic_name'],
            },
        ),
        migrations.AddField(
            model_name='slot',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='slots', to='home.topic'),
        ),
    ]
