# Generated by Django 4.2.9 on 2025-02-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_slot_topic_slot_maximum_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
