# Generated by Django 4.2.9 on 2025-02-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_topic_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='slot_id',
            field=models.CharField(default=-2025, editable=False, help_text='Unique 5-digit slot identifier', max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
