# Generated by Django 4.2.9 on 2025-02-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_slot_slot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='booking_status',
            field=models.CharField(choices=[('start', 'Start'), ('pause', 'Pause')], default='pause', max_length=5, verbose_name='Booking Status'),
        ),
    ]
