# Generated by Django 4.2.9 on 2025-02-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_slot_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='roomid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Room ID'),
        ),
        migrations.AddField(
            model_name='slot',
            name='start_status',
            field=models.CharField(choices=[('start', 'Start'), ('pause', 'Pause'), ('end', 'End')], default='pause', max_length=10, verbose_name='Start Status'),
        ),
    ]
