# Generated by Django 4.2.9 on 2025-02-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_slot_roomid_slot_start_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='roomid',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Room ID'),
        ),
    ]
