# Generated by Django 4.2.9 on 2025-02-24 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_room_roomparticipant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='score',
        ),
        migrations.RemoveField(
            model_name='roomparticipant',
            name='score',
        ),
        migrations.RemoveField(
            model_name='roomparticipant',
            name='team_number',
        ),
        migrations.AddField(
            model_name='room',
            name='total_groups',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='group_name',
            field=models.CharField(default='A00', help_text='Alphabetic group identifier (e.g., A12, B45)', max_length=3),
        ),
    ]
