# Generated by Django 4.2.9 on 2025-02-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_userscore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserScore',
        ),
    ]
