# Generated by Django 4.2.9 on 2025-02-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_delete_userscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomparticipant',
            name='join_time',
        ),
        migrations.RemoveField(
            model_name='roomparticipant',
            name='leave_time',
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='joined',
            field=models.BooleanField(default=False, help_text='Indicates if the user has joined the room'),
        ),
        migrations.AlterField(
            model_name='roomparticipant',
            name='participation_status',
            field=models.CharField(choices=[('registered', 'Registered'), ('completed', 'Completed')], default='registered', max_length=20),
        ),
    ]
