# Generated by Django 4.2.9 on 2025-02-24 14:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_roomparticipant_join_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='A00', help_text='Alphabetic group identifier (e.g., A12, B45)', max_length=3)),
                ('participation_status', models.CharField(choices=[('registered', 'Registered'), ('completed', 'Completed')], default='registered', max_length=20)),
                ('joined', models.BooleanField(default=False, help_text='Indicates if the user has joined the slot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slot Participant',
                'verbose_name_plural': 'Slot Participants',
            },
        ),
        migrations.AlterUniqueTogether(
            name='roomparticipant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='roomparticipant',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomparticipant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='roomid',
        ),
        migrations.AddField(
            model_name='slot',
            name='room_status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='closed', max_length=10, verbose_name='Room Status'),
        ),
        migrations.AddField(
            model_name='slot',
            name='total_groups',
            field=models.PositiveIntegerField(default=0, help_text='Number of groups in this slot', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='slot',
            name='booking_status',
            field=models.CharField(choices=[('start', 'Start'), ('pause', 'Pause'), ('end', 'End')], default='pause', max_length=5, verbose_name='Booking Status'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomParticipant',
        ),
        migrations.AddField(
            model_name='slotparticipant',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='home.slot'),
        ),
        migrations.AddField(
            model_name='slotparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_participations', to='home.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='slotparticipant',
            unique_together={('slot', 'user')},
        ),
    ]
