# Generated by Django 4.2.9 on 2025-02-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_slotparticipant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='booking_status',
        ),
    ]
