# Generated by Django 4.2.9 on 2025-02-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_remove_slot_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='voting',
            field=models.CharField(blank=True, choices=[('start', 'Start'), ('end', 'End')], help_text='Voting status for the participant', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='slotparticipant',
            name='mark',
            field=models.PositiveIntegerField(blank=True, help_text='Mark assigned to the participant', null=True),
        ),
    ]
