# Generated by Django 4.2.9 on 2025-02-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_slot_voting_slotparticipant_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='voting',
        ),
        migrations.AddField(
            model_name='slotparticipant',
            name='voting',
            field=models.CharField(blank=True, choices=[('start', 'Start'), ('end', 'End')], help_text='Voting status for the participant', max_length=5, null=True),
        ),
    ]
