# Generated by Django 4.2.9 on 2025-02-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_slot_voting_slotparticipant_voting'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotparticipant',
            name='topic',
            field=models.CharField(default='-', help_text='Alphabetic group identifier (e.g., A12, B45)', max_length=500),
        ),
    ]
