# Generated by Django 4.2.9 on 2025-02-27 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_slotparticipant_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotparticipant',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.topic'),
        ),
    ]
