# Generated by Django 4.2.9 on 2025-02-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_userprofile_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('STUDENT', 'STUDENT'), ('FACULTY', 'FACULTY')], max_length=50, null=True),
        ),
    ]
