# Generated by Django 4.2.9 on 2025-02-27 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='alloted_staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'FACULTY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_slots', to='home.userprofile', verbose_name='Staff Name'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='staff_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Staff ID'),
        ),
    ]
