# Generated by Django 4.2.9 on 2025-02-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_slot_alloted_staff_alter_slot_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
