# Generated by Django 4.2.9 on 2025-02-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_userprofile_roll_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotparticipant',
            name='voting',
        ),
        migrations.AddField(
            model_name='slotparticipant',
            name='voting_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
    ]
