# Generated by Django 4.2.9 on 2025-03-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_remove_slotparticipant_voting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.TextField(max_length=3000, unique=True),
        ),
    ]
