# Generated by Django 4.2.9 on 2025-03-02 07:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_topic_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='total_rankings',
            field=models.PositiveIntegerField(default=3, help_text='Total number of ranking positions', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='SlotRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(help_text='Rank position (1st, 2nd, 3rd, etc.)', validators=[django.core.validators.MinValueValidator(1)])),
                ('score', models.PositiveIntegerField(help_text='Score value for this rank', validators=[django.core.validators.MinValueValidator(0)])),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_ranks', to='home.slot')),
            ],
            options={
                'verbose_name': 'Slot Rank',
                'verbose_name_plural': 'Slot Ranks',
                'ordering': ['slot', 'rank'],
                'unique_together': {('slot', 'rank')},
            },
        ),
    ]
