# Generated by Django 4.2.9 on 2025-03-02 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_slot_total_rankings_slotrank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotrank',
            name='rank',
            field=models.PositiveIntegerField(blank=True, help_text='Rank position (1st, 2nd, 3rd, etc.)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='slotrank',
            name='score',
            field=models.PositiveIntegerField(blank=True, help_text='Score value for this rank', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
