# Generated by Django 4.2.9 on 2025-03-02 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_alter_slotrank_rank_alter_slotrank_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotrank',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_ranks', to='home.slot'),
        ),
    ]
