# Generated by Django 4.2.9 on 2025-03-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_slotrank_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotparticipant',
            name='voting_progress',
            field=models.JSONField(blank=True, help_text='Stores voting progress and marks for each question', null=True),
        ),
    ]
