# Generated by Django 4.2.9 on 2025-03-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0045_slot_eligible_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='eligible_groups',
        ),
        migrations.AddField(
            model_name='levels',
            name='eligible_groups',
            field=models.ManyToManyField(blank=True, help_text='If empty, slot is available to everyone. Otherwise, only specified groups are eligible.', related_name='eligible_slots', to='auth.group'),
        ),
    ]
