# Generated by Django 4.2.9 on 2025-03-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0046_remove_slot_eligible_groups_levels_eligible_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eligible_groups',
            field=models.ManyToManyField(blank=True, help_text='If empty, slot is available to everyone. Otherwise, only specified groups are eligible.', related_name='events', to='auth.group'),
        ),
    ]
