# Generated by Django 4.2.9 on 2025-03-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_alter_event_eligible_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotparticipant',
            name='request_voting',
            field=models.CharField(choices=[('request', 'Request'), ('unrequest', 'Unrequest')], default='unrequest', help_text='Indicates if the participant has requested to start voting', max_length=20),
        ),
    ]
