# Generated by Django 4.2.9 on 2025-03-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_slotparticipant_request_voting'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='absent_penalty',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Penalty for absent members (highest rank score × team size)', max_digits=5),
        ),
        migrations.AddField(
            model_name='slot',
            name='biasing_penalty',
            field=models.DecimalField(decimal_places=1, default=2.0, help_text='Penalty for biased voting behavior', max_digits=5),
        ),
        migrations.AddField(
            model_name='slot',
            name='deviation_threshold',
            field=models.DecimalField(decimal_places=1, default=2.0, help_text='Threshold for acceptable deviation in votes', max_digits=5),
        ),
    ]
