# Generated by Django 4.2.9 on 2025-03-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_slot_absent_penalty_slot_biasing_penalty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='absent_penalty',
        ),
    ]
