# Generated by Django 4.2.9 on 2025-03-08 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_remove_slot_absent_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='filled_capacity',
            field=models.PositiveIntegerField(default=0, help_text='Filled capacity in the venue', validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
