# Generated by Django 4.2.9 on 2025-03-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_venue_filled_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='slot_type',
            field=models.CharField(choices=[('Regular', 'Regular Slot'), ('Quick Slot', 'Quick Slot')], default='Regular Slot', max_length=20, verbose_name='Slot type'),
        ),
    ]
