# Generated by Django 4.2.9 on 2025-03-10 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_slot_slot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user__groups__name__in': ['faculty', 'slot creator', 'slot host', 'quick slot creator']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_slots', to='home.userprofile', verbose_name='Created By'),
        ),
    ]
