# Generated by Django 4.2.9 on 2025-03-10 15:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_slot_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='maximum_capacity',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Maximum number of participants', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='slot',
            name='team_size',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Number of participants per team', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='slot',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='home.venue'),
        ),
    ]
