# Generated by Django 4.2.9 on 2025-03-10 16:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_alter_slot_maximum_capacity_alter_slot_team_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quick_slot_id', models.CharField(editable=False, help_text='Unique identifier for the quick slot', max_length=9, unique=True)),
                ('no_of_groups', models.PositiveIntegerField(default=1, help_text='Number of groups in this quick slot session', validators=[django.core.validators.MinValueValidator(1)])),
                ('slot_ranking', models.PositiveIntegerField(default=3, help_text='Default ranking position for this quick slot', validators=[django.core.validators.MinValueValidator(1)])),
                ('slot_status', models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed')], default='opened', max_length=10, verbose_name='Slot Status')),
                ('total_ranking', models.PositiveIntegerField(default=3, help_text='Total number of ranking positions', validators=[django.core.validators.MinValueValidator(1)])),
                ('biasing_penalty', models.DecimalField(decimal_places=1, default=2.0, help_text='Penalty for biased voting behavior', max_digits=5)),
                ('deviation_threshold', models.DecimalField(decimal_places=1, default=2.0, help_text='Threshold for acceptable deviation in votes', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(limit_choices_to={'user__groups__name__in': ['faculty', 'slot creator', 'slot host', 'quick slot creator']}, on_delete=django.db.models.deletion.CASCADE, related_name='quick_slots_created', to='home.userprofile', verbose_name='Created By')),
                ('slot_participants', models.ManyToManyField(blank=True, related_name='quick_slot_participations', to='home.userprofile', verbose_name='Slot Participants')),
            ],
            options={
                'verbose_name': 'Quick Slot',
                'verbose_name_plural': 'Quick Slots',
                'ordering': ['-created_at'],
            },
        ),
    ]
