# Generated by Django 4.2.9 on 2025-03-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_remove_quickslots_biasing_penalty_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quickslotsgroups',
            options={'ordering': ['quick_slot', 'group_name'], 'verbose_name': 'Quick Slot Group', 'verbose_name_plural': 'Quick Slot Groups'},
        ),
        migrations.AlterUniqueTogether(
            name='quickslotsgroups',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='quickslotsgroups',
            name='group_name',
            field=models.CharField(default='-', help_text="Name of the group (e.g., 'Group A', 'Team 1')", max_length=50, verbose_name='Group Name'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='quickslotsgroups',
            unique_together={('quick_slot', 'group_name')},
        ),
    ]
