# Generated by Django 4.2.9 on 2025-03-10 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_alter_quickslotsgroups_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickslotsgroups',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_slot_groups', to='home.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='quickslotsgroups',
            name='group_name',
            field=models.CharField(help_text="Name of the group (e.g., 'A45', 'B27')", max_length=50, verbose_name='Group Name'),
        ),
        migrations.AlterField(
            model_name='quickslotsgroups',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_slot_groups', to='home.levels', verbose_name='Level'),
        ),
    ]
