# Generated by Django 4.2.9 on 2025-03-11 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_alter_quickslotsgroups_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickslotsgroups',
            name='room_status',
        ),
        migrations.AddField(
            model_name='quickslotsgroups',
            name='joined',
            field=models.BooleanField(default=False, verbose_name='Joined'),
        ),
        migrations.AddField(
            model_name='quickslotsgroups',
            name='participation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('joined', 'Joined'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Participation Status'),
        ),
        migrations.AddField(
            model_name='quickslotsgroups',
            name='request_voting',
            field=models.CharField(choices=[('none', 'None'), ('request', 'Requested'), ('approved', 'Approved'), ('declined', 'Declined')], default='none', max_length=20, verbose_name='Request Voting'),
        ),
        migrations.AddField(
            model_name='quickslotsgroups',
            name='voting_progress',
            field=models.PositiveIntegerField(default=0, help_text='Voting progress percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Voting Progress'),
        ),
        migrations.AddField(
            model_name='quickslotsgroups',
            name='voting_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20, verbose_name='Voting Status'),
        ),
    ]
