# Generated by Django 4.2.9 on 2025-03-11 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_remove_quickslotsgroups_room_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickslotsgroups',
            name='joined',
        ),
        migrations.RemoveField(
            model_name='quickslotsgroups',
            name='participation_status',
        ),
        migrations.RemoveField(
            model_name='quickslotsgroups',
            name='quick_slot_participants',
        ),
        migrations.RemoveField(
            model_name='quickslotsgroups',
            name='request_voting',
        ),
        migrations.RemoveField(
            model_name='quickslotsgroups',
            name='voting_progress',
        ),
        migrations.RemoveField(
            model_name='quickslotsgroups',
            name='voting_status',
        ),
    ]
