# Generated by Django 4.2.9 on 2025-03-11 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_remove_quickslotsgroups_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickSlotParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_status', models.CharField(choices=[('registered', 'Registered'), ('completed', 'Completed')], default='registered', max_length=20)),
                ('joined', models.BooleanField(default=False, help_text='Indicates if the user has joined the quick slot group')),
                ('voting_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('request_voting', models.CharField(choices=[('request', 'Request'), ('unrequest', 'Unrequest')], default='unrequest', help_text='Indicates if the participant has requested to start voting', max_length=20)),
                ('voting_progress', models.JSONField(blank=True, help_text='Stores voting progress and marks for each question', null=True)),
                ('mark', models.PositiveIntegerField(blank=True, help_text='Mark assigned to the participant', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quick Slot Participant',
                'verbose_name_plural': 'Quick Slot Participants',
            },
        ),
        migrations.AlterModelOptions(
            name='slotrank',
            options={'ordering': ['rank'], 'verbose_name': 'Slot Rank', 'verbose_name_plural': 'Slot Ranks'},
        ),
        migrations.AlterUniqueTogether(
            name='slotrank',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='slotrank',
            name='quick_slot_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='home.quickslotsgroups'),
        ),
        migrations.AddConstraint(
            model_name='slotrank',
            constraint=models.UniqueConstraint(condition=models.Q(('slot__isnull', False)), fields=('slot', 'rank'), name='unique_slot_rank'),
        ),
        migrations.AddConstraint(
            model_name='slotrank',
            constraint=models.UniqueConstraint(condition=models.Q(('quick_slot_group__isnull', False)), fields=('quick_slot_group', 'rank'), name='unique_quick_slot_group_rank'),
        ),
        migrations.AddField(
            model_name='quickslotparticipant',
            name='quick_slot_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='home.quickslotsgroups'),
        ),
        migrations.AddField(
            model_name='quickslotparticipant',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.topic'),
        ),
        migrations.AddField(
            model_name='quickslotparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_slot_participations', to='home.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='quickslotparticipant',
            unique_together={('quick_slot_group', 'user')},
        ),
    ]
