# Generated by Django 4.2.9 on 2025-03-11 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_quickslotparticipant_alter_slotrank_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickslotsgroups',
            name='max_capacity',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of participants allowed in this group', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
