# Generated by Django 4.2.9 on 2025-03-11 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_alter_quickslotsgroups_max_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickslotsgroups',
            name='max_capacity',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of participants allowed in this group', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
