# Generated by Django 4.2.9 on 2025-03-12 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_alter_quickslotsgroups_max_capacity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quickslotparticipant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='quickslotparticipant',
            name='quick_slot_group',
        ),
        migrations.RemoveField(
            model_name='quickslotparticipant',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='quickslotparticipant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quickslots',
            name='created_by',
        ),
        migrations.AlterUniqueTogether(
            name='quickslotsgroups',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='quickslotsgroups',
            name='event',
        ),
        migrations.RemoveField(
            model_name='quickslotsgroups',
            name='level',
        ),
        migrations.RemoveField(
            model_name='quickslotsgroups',
            name='quick_slot',
        ),
        migrations.RemoveField(
            model_name='quickslotsgroups',
            name='topic',
        ),
        migrations.AlterModelOptions(
            name='slotrank',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='slotrank',
            name='unique_slot_rank',
        ),
        migrations.RemoveConstraint(
            model_name='slotrank',
            name='unique_quick_slot_group_rank',
        ),
        migrations.RemoveField(
            model_name='slotrank',
            name='quick_slot_group',
        ),
        migrations.DeleteModel(
            name='QuickSlotParticipant',
        ),
        migrations.DeleteModel(
            name='QuickSlots',
        ),
        migrations.DeleteModel(
            name='QuickSlotsGroups',
        ),
    ]
