# Generated by Django 4.2.9 on 2025-03-12 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_alter_quickslotparticipant_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlotRank',
        ),
    ]
