# Generated by Django 4.2.9 on 2025-03-12 06:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_delete_slotrank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'verbose_name': 'Slot', 'verbose_name_plural': 'Slots'},
        ),
        migrations.AlterUniqueTogether(
            name='slotparticipant',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='slot',
            name='alloted_staff',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='biasing_penalty',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='booked_users',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='deviation_threshold',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='event',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='filled_capacity',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='level',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='maximum_capacity',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='remaining_capacity',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='room_status',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='slot_date',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='slot_endtime',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='slot_starttime',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='slot_type',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='start_status',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='team_size',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='total_groups',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='total_rankings',
        ),
        migrations.AddField(
            model_name='slotparticipant',
            name='finished_level',
            field=models.BooleanField(default=False, help_text='Indicates if the user has completed this level'),
        ),
        migrations.AddField(
            model_name='slotparticipant',
            name='participant_status',
            field=models.CharField(choices=[('on_going', 'On Going'), ('completed', 'Completed')], default='on_going', max_length=20),
        ),
        migrations.AlterField(
            model_name='slot',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'FACULTY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_slots', to='home.userprofile', verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='slot_status',
            field=models.CharField(choices=[('live', 'Live'), ('expired', 'Expired')], default='live', max_length=10),
        ),
        migrations.AlterField(
            model_name='slotparticipant',
            name='group_name',
            field=models.CharField(help_text='Alphabetic group identifier (e.g., A12, B45)', max_length=3),
        ),
        migrations.AlterField(
            model_name='slotparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='home.userprofile'),
        ),
        migrations.AlterField(
            model_name='slotparticipant',
            name='voting_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='not_started', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='slotparticipant',
            unique_together={('slot', 'group_name', 'user')},
        ),
        migrations.RemoveField(
            model_name='slotparticipant',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='slotparticipant',
            name='participation_status',
        ),
        migrations.RemoveField(
            model_name='slotparticipant',
            name='request_voting',
        ),
        migrations.CreateModel(
            name='SlotGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(help_text='Alphabetic group identifier (e.g., A12, B45)', max_length=3)),
                ('total_rankings', models.PositiveIntegerField(default=3, help_text='Total number of ranking positions', validators=[django.core.validators.MinValueValidator(1)])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField()),
                ('start_status', models.CharField(choices=[('start', 'Start'), ('pause', 'Pause'), ('end', 'End')], default='pause', max_length=10, verbose_name='Start Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_groups', to='home.event')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_groups', to='home.levels')),
                ('participants', models.ManyToManyField(blank=True, related_name='groups', to='home.userprofile')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='home.slot')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_groups', to='home.topic')),
            ],
            options={
                'verbose_name': 'Slot Group',
                'verbose_name_plural': 'Slot Groups',
                'unique_together': {('slot', 'group_name')},
            },
        ),
    ]
