# Generated by Django 4.2.9 on 2025-03-12 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_alter_slot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotgroup',
            name='total_rankings',
            field=models.PositiveIntegerField(blank=True, default=3, help_text='Total number of ranking positions', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
