# Generated by Django 4.2.9 on 2025-03-13 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_alter_slotgroup_total_rankings'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'user__groups__name__in': ['faculty', 'slot host', 'slot creator']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_slots_new', to='home.userprofile', verbose_name='Assigned To'),
        ),
    ]
