# Generated by Django 4.2.9 on 2025-03-13 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_alter_slotgroup_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotgroup',
            name='group_name',
            field=models.CharField(help_text='Alphabetic group identifier (e.g., A12, B45)', max_length=4),
        ),
        migrations.AlterField(
            model_name='slotparticipant',
            name='group_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_participants', to='home.slotgroup'),
        ),
    ]
