# Generated by Django 4.2.9 on 2025-03-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_alter_slotparticipant_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotparticipant',
            name='mark',
            field=models.PositiveIntegerField(blank=True, help_text='Mark assigned to the participant', null=True),
        ),
    ]
