# Generated by Django 4.2.9 on 2025-03-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0075_slotparticipant_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotparticipant',
            name='mark',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Mark assigned to the participant', null=True),
        ),
    ]
