# Generated by Django 4.2.9 on 2025-03-18 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0076_alter_slotparticipant_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotparticipant',
            name='mark',
            field=models.FloatField(blank=True, default=0, help_text='Mark assigned to the participant', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
