# Generated by Django 4.2.9 on 2025-03-20 14:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0077_alter_slotparticipant_mark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievements',
            options={'ordering': ['event', 'level', 'rank'], 'verbose_name': 'Achievement', 'verbose_name_plural': 'Achievements'},
        ),
        migrations.AlterUniqueTogether(
            name='achievements',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='achievements',
            name='group_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='achievements',
            name='mark',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achievements',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achievements',
            name='slot_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='achievements',
            unique_together={('user', 'finished_level', 'slot_id', 'group_name')},
        ),
    ]
