# Generated by Django 4.2.9 on 2025-03-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0078_alter_achievements_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievements',
            options={'ordering': ['event', 'level', '-mark'], 'verbose_name': 'Achievement', 'verbose_name_plural': 'Achievements'},
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='rank',
        ),
    ]
