# Generated by Django 4.2.9 on 2025-03-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0079_alter_achievements_options_remove_achievements_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Telegram chat ID for notifications', max_length=50, null=True),
        ),
    ]
