# Generated by Django 4.2.9 on 2025-03-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0080_userprofile_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotgroup',
            name='finished',
            field=models.BooleanField(default=False, help_text='Indicates whether the group has completed all its activities', verbose_name='Group Finished'),
        ),
    ]
