# Generated by Django 4.2.9 on 2025-03-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0081_slotgroup_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotparticipant',
            name='group_name',
            field=models.CharField(help_text='Alphabetic group identifier (e.g., A12, B45)', max_length=10),
        ),
    ]
