# Generated by Django 4.2.9 on 2025-03-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0082_alter_slotparticipant_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotgroup',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
