# Generated by Django 4.2.9 on 2025-03-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_slotgroup_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotparticipant',
            name='request_voting',
            field=models.CharField(choices=[('request', 'request'), ('not_requested', 'not_requested')], default='not_requested', max_length=20),
        ),
    ]
