# Generated by Django 4.2.9 on 2025-03-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0084_slotparticipant_request_voting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotparticipant',
            name='mark',
            field=models.FloatField(blank=True, default=0, help_text='Mark assigned to the participant', null=True),
        ),
    ]
