# Generated by Django 4.2.9 on 2025-03-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0085_alter_slotparticipant_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotparticipant',
            name='mark',
            field=models.FloatField(blank=True, help_text='Mark assigned to the participant', null=True),
        ),
    ]
