# Generated by Django 4.2.9 on 2025-03-27 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0086_alter_slotparticipant_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, help_text='External link to the material', null=True)),
                ('pdf_file', models.FileField(blank=True, help_text='PDF file for the material', null=True, upload_to='materials/pdfs/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_users', models.ManyToManyField(blank=True, help_text='Users who have completed this material', related_name='completed_materials', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='home.event')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='home.levels')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'ordering': ['-created_at'],
            },
        ),
    ]
