# Generated by Django 4.2.9 on 2025-03-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0087_materials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='description',
        ),
    ]
