# Generated by Django 4.2.9 on 2025-03-27 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0088_remove_materials_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='title',
        ),
    ]
