# Generated by Django 4.2.9 on 2025-03-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0089_remove_materials_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='title',
            field=models.CharField(default='material', max_length=200),
            preserve_default=False,
        ),
    ]
